apiVersion: apps/v1
kind: Deployment

metadata:
  name: mydeployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: dheeraj

  template:
    metadata:
      labels:
        app: dheeraj

    spec:
      containers:
        - name: my-website
          image: dhankhar9918/deploytokubenetes:dheeraj

          ports:
            - containerPort: 80